### PR TITLE
fix: add labelText prop support to TextInput component

### LINKED ISSUE #894: 🐛 Bug - Wrong output for Aria-Label on TextInput Component
# Forma 36 bug report

## Summary

During first steps (im fairly new to contentful) inside the app framework and using forma-36 I discovered a bug inside:
https://github.com/contentful/forma-36/blob/master/packages/forma-36-react-components/src/components/TextInput/TextInput.tsx

The TextInput-Component doesn't have a labelText-prop like other component (e.g. ControlledInput).
And instead of using this missing prop for arial-label, the name-prop is used instead.

```javascript
<input
        onKeyDown={handleKeyDown}
        aria-label={name}
        ...
      />
```

How this works now? Should I fix this and open a PullRequest?

## Environment

Environment independent

## Expected results

The component prop labelText on TextField Component is used as aria-label on rendered <input>-Tag

## Actual results

```javascript
  <TextField
    name="authToken"
    id="authToken"
    labelText="Authentication Token" // should be aria-label
    value={eurotext || ''}
    onChange={(e) =>
      this.setState({
        parameters: {
          ...this.state.parameters,
          eurotext: (e.target as HTMLTextAreaElement).value,
        },
      })
    }
    helpText="Authentication token for private rest api."
  />
```
But on the actual rendered element it uses the name-prop instead
image

### PR DESCRIPTION
**Pull request by mshaaban0**
# Purpose of PR

fixes #894

Addressed originally in #971 

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

File: packages/forma-36-react-components/src/components/TextInput/TextInput.tsx [hunk 1]
```diff
@@ -26,6 +26,7 @@ export type TextInputProps = {
     | 'date'
     | 'time';
   name?: string;
+  labelText?: string;
```
Comment (nikazawila) [inline packages/forma-36-react-components/src/components/TextInput/TextInput.tsx:29]: massive nit: personally, I'd expect a label to show up along the input if I used that `labelText` prop and not for it to just be an aria-label.

**Review by nikazawila — APPROVED** [review]

File: packages/forma-36-react-components/src/components/TextInput/TextInput.tsx (hunk 1 above)
Comment (mshaaban0) [reply packages/forma-36-react-components/src/components/TextInput/TextInput.tsx:29]: we went with `labelText` as this fix for v3, and this how it used on TextField, in v4 however, It's renamed to `label` which resolve to `aria-label` :) but I agree, it's a bit confusing
