### PR TITLE
fix(accordion): make AccordionPanel height adjustable to content

### LINKED ISSUE #962: 🐛 Bug - AccordionItem doesn't resize after content dynamic content changes
# Forma 36 bug report

## Summary
Accordion Item not resizing for dynamically changed content

## Environment
Google Chrome 90.0.4430.93

## Steps to reproduce

1. create sidebar app
2. added AccordionItem to it
3. Inside AccorditionItem render JSON output
4. Open JSON attributes
5. Content disappears under the next AccordionItem (see the attached video, https://user-images.githubusercontent.com/59477906/117800484-77fc8680-b253-11eb-903f-24bfa33e9510.mov)

I can also invite you to space where we are running the app for better troubleshooting

## Expected results
The additional content inside the AccordionItem would automatically increase the height to what is displayed inside.

## Actual results
Content is being cut off. Opening and closing the AccordionItem leads to the correct result.

### PR DESCRIPTION
**Pull request by bgutsol**
# Purpose of PR
Make `AccordionPanel` height dynamically adjustable to its content. So whenever content size changes the height of `AccordionPanel` adapt to it.

Closes #962 

## PR Checklist

- [x] I have read the relevant `readme.md` file(s)
- [x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [x] Tests are added/updated/not required
- [x] Tests are passing
- [x] Storybook stories are added/updated/not required
- [x] Usage notes are added/updated/not required
- [x] Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
- [x] Doesn't contain any sensitive information

### CODE REVIEW

**Review by denkristoffer — APPROVED** [review]
Great!

File: packages/forma-36-react-components/src/components/Accordion/AccordionPanel/AccordionPanel.tsx [hunk 1]
```diff
@@ -26,29 +25,54 @@ export const AccordionPanel: FC<AccordionPanelProps> = ({
...
+  const getPanelContentHeight = () => {
+    const { current } = panelEl;
+
+    if (!current) {
+      // to keep the function return type as string only and
+      // not overcomplicate things with non-nullable checks
+      return '0px';
+    }
+
+    return `${current.scrollHeight / 16}rem`; // converting height pixels into rem
```
Comment (denkristoffer) [inline packages/forma-36-react-components/src/components/Accordion/AccordionPanel/AccordionPanel.tsx:37]: This should probably use the `fontBaseDefault` token.

**Review by denkristoffer — CHANGES_REQUESTED** [review]

File: packages/forma-36-react-components/src/components/Accordion/AccordionPanel/AccordionPanel.tsx (hunk 1 above)
Comment (bgutsol) [reply packages/forma-36-react-components/src/components/Accordion/AccordionPanel/AccordionPanel.tsx]: Fixed, thanks for the comment.

**Review by denkristoffer — APPROVED** [review]

**Review by thebesson — APPROVED** [review]
